---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-resource
  type: pivnet
  source:
    api_token: {{pivnet-token}}
    product_slug: platform-automation

- name: customizations
  type: git
  source:
    uri: https://github.com/ebrusseau/customize-pcf-automation-image.git

- name: custom-image
  type: docker-image
  source:
    repository: ebrusseau/custom-pcf-automation
    tag: latest
    username: {{docker-username}}
    password: {{docker-password}}

jobs:
- name: customize-image
  plan:
    - get: customizations
    - get: platform-automation-image
      resource: platform-automation-resource
      params:
        globs: [ "platform-automation-image*.tgz" ]
        unpack: true

    - task: setup-docker-import
      file: setup-docker-import-task.yml

    - put: custom-image
      params:
        load_base: docker-image
        build: customizations
